import datetime
import time
d=datetime.datetime(2021,5,23,11,5,20)
print(d)
d=datetime.datetime.today()
print("datetime=",d)
print("now=",datetime.datetime.now())
print("utcnow=",datetime.datetime.utcnow())
print("astime=",d.astimezone())
print("tzname=",d.tzname())
print("min=",datetime.datetime.min)
print("max=",datetime.datetime.max)
print("resolution=",datetime.datetime.resolution)
print("hour=",d.hour)
print("minute=",d.minute)
print("second=",d.second)
print("microsecond=",d.microsecond)
print("year=",d.year)
print("month=",d.month)
print("day=",d.day)
print("timetuple=",d.timetuple())
