import datetime
import time
d=datetime.date(2021,6,24)
print("current date=",d)
print(d.strftime("%c"))
print("today=",datetime.date.today())
print("timestamp=",datetime.date.fromtimestamp(time.time()))
print("min=",datetime.date.min)
print("max=",datetime.date.max)
print("resolution=",datetime.date.resolution)
print("year=",d.year)
print("month=",d.month)
print("day=",d.day)
print("date after replace=",d.replace(year=2022,month=6,day=13))
print("time tuple=",d.timetuple())
print("weekday=",d.weekday())
print("isoweekday=",d.isoweekday())
print("isocalendar=",d.isocalendar())
print("isoformat=",d.isoformat())
print("str=",d.__str__())
print("ctime=",d.ctime())
