s="hello world"
print("before:",s)
print("capitalize:",s.capitalize())
print("after:",s)
print("title:",s.title())
print("center:",s.center(15,'*'))
print("ljust:",s.ljust(15,'*'))
print("rjust:",s.rjust(15,'*'))
print("count:",s.count('l',0,len(s)))
print("count:",s.count("l",0,5))
print("find:",s.find('l',0,len(s)))
print("Rfind:",s.rfind('l',0,len(s)))
print("find:",s.find('a',0,len(s)))
print("index:",s.index('l',0,len(s)))
print("Rindex:",s.rindex('l',0,len(s)))
